spring:
    prfiles:
        active: dev
---
server:
    port: 8201
#spring的配置
spring:
  prfiles: dev
  application:
    name: springcloud-provider-dept

#Eureka配置,服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/


---
server:
    port: 8202
#spring的配置
spring:
  prfiles: test
  application:
    name: springcloud-provider-test

#Eureka配置,服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/