spring:
    profiles:
        active: dev
---
server:
  port: 7001
  
spring:
  prfiles: dev
  application:
    name: springcloud-config-rureka

#eureka
eureka:
  instance:
    hostname: eureka7001.com #Eureka服务端的实例名称
  client:
    register-with-eureka: false #是否向eureka注册中心注册自己
    fetch-registry: false #表示如果为false，标志自己为注册中心
    service-url:
      #单机情况：http://${eureka.instance.hostname}:${server.port}/eureka/
      #集群情况：（关联）
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
---
server:
  port: 7001
  
spring:
  prfiles: test
  application:
    name: springcloud-config-rureka

#eureka
eureka:
  instance:
    hostname: eureka7001.com #Eureka服务端的实例名称
  client:
    register-with-eureka: false #是否向eureka注册中心注册自己
    fetch-registry: false #表示如果为false，标志自己为注册中心
    service-url:
      #单机情况：http://${eureka.instance.hostname}:${server.port}/eureka/
      #集群情况：（关联）
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
---